---
- name: install commons
  apt: "pkg={{ item }} state=installed"
  with_items:
    - htop
    - curl
    - hexchat
    - build-essential
    - astyle
    - inotify-tools

- name: Configure inotify-tools
  shell: "sysctl -w fs.inotify.max_user_watches=100000"
