---
- name: bootstrap for lubuntu sandbox
  hosts: local
  become: True

  vars:
    - user: "sd"
    - user_groups:
        - adm
        - docker
    - git_user_email: "stevenmichaeldevine@gmail.com"
    - git_user_name: "Steven Devine"
    - apt_packages:
      - curl
      - build-essential
      - errno
      - gitk
      - vagrant
      - openjdk-8-jre
    - php_enable_webserver: false
    - php_default_version_debian: "7.2"
    - php_packages:
        - php7.2-zip

  pre_tasks:
    - name: apt-get update
      apt:
        autoremove: true
        update_cache: true
        cache_valid_time: 86400
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
    - name: install basics
      apt:
        name: "{{ apt_packages }}"
    - name: admin no sudo password
      lineinfile:
        path: /etc/sudoers
        state: present
        line: '%adm ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
    - name: add user to groups
      user:
        name: '{{ user }}'
        groups: "{{user_groups}}"
        append: yes
    - name: Git global config
      shell: "git config --global {{item}}"
      with_items:
        - 'user.email {{git_user_email}}'
        - 'user.name {{git_user_name}}'
        - 'push.default simple'
    - name: bash ps1
      copy: src=./.bash-git-ps1 dest=/home/{{user}}/.bash-git-ps1
    - name: bash ps1
      lineinfile: dest=/home/{{user}}/.bashrc line="source ~/.bash-git-ps1" state=present
    - name: bash aliases
      copy: src=./.bash-aliases dest=/home/{{user}}/.bash-aliases
    - name: bash ps1
      lineinfile: dest=/home/{{user}}/.bashrc line="source ~/.bash-aliases" state=present
    - name: vimrc
      copy: src=./.vimrc dest=/home/{{user}}/.vimrc

  roles:
          #- geerlingguy.docker
          #- geerlingguy.php
          #- geerlingguy.php-xdebug
