---
- name: bootstrap for lubuntu sandbox
  hosts: local
  sudo: True

  vars:
    - user: "sd"

  pre_tasks:
    - name: apt-get update
      apt: update_cache=yes cache_valid_time=86400
    - name: apt-get autoremove
      register: autoremove
      shell: "apt-get -y autoremove | wc -l"
      changed_when: autoremove.stdout > '4'

  roles:
