---
- name: bootstrap for lubuntu sandbox
  hosts: localhost
  gather_facts: yes

  vars:
    - user_groups:
        - adm
        - docker
    - git_user_email: "stevenmichaeldevine@gmail.com"
    - git_user_name: "Steven Devine"
    - apt_packages:
      - curl
      - build-essential
      - errno
      - gitk
      - vagrant
      - docker.io
    - jetbrains_toolbox_version: latest

  pre_tasks:
    - name: apt-get update
      become: yes
      apt:
        autoremove: true
        update_cache: true
        cache_valid_time: 86400
    - name: Upgrade all packages to the latest version
      become: yes
      apt:
        upgrade: dist
    - name: install basics
      become: yes
      apt:
        name: "{{apt_packages}}"
    - name: admin no sudo password
      become: yes
      lineinfile:
        path: /etc/sudoers
        state: present
        line: '%adm ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
    - name: add user to groups
      become: yes
      user:
        name: '{{ansible_user_id}}'
        groups: "{{user_groups}}"
        append: yes
    - name: gitconfig
      copy: src=./gitconfig dest=/home/{{ansible_user_id}}/.gitconfig
    - name: bash ps1 file
      copy: src=./bash-git-ps1 dest=/home/{{ansible_user_id}}/.bash-git-ps1
    - name: bash ps1 reference
      lineinfile: dest=/home/{{ansible_user_id}}/.bashrc line="source ~/.bash-git-ps1" state=present
    - name: bash aliases file
      copy: src=./bash-aliases dest=/home/{{ansible_user_id}}/.bash-aliases
    - name: bash ps1 reference
      lineinfile: dest=/home/{{ansible_user_id}}/.bashrc line="source ~/.bash-aliases" state=present
    - name: vimrc 
      copy: src=./vimrc dest=/home/{{ansible_user_id}}/.vimrc

  roles:
    - jaredhocutt.jetbrains_toolbox
