---
- name: Update apt
  apt: update_cache=yes cache_valid_time=3600

- name: Install common apps
  apt: "pkg={{ item }} state=installed"
  with_items:
    - curl
    - git
    - gitk
    - chromium-browser
    - virtualbox
    - vagrant 
