---
- name: "Install PHP"
  apt: pkg={{item}} state=latest
  with_items:
    - php5-cli
    - php5-json
    - php5-mcrypt

- name: "Check for Composer"
  stat: path=/usr/local/bin/composer
  register: composer

- name: "Download Composer"
  shell: "curl -sS https://getcomposer.org/installer | php -- --install-dir=/tmp"
  when: composer.stat.exists == false

- name: "Install Composer"
  copy: src=/tmp/composer.phar dest=/usr/local/bin/composer mode=0550 owner="{{user}}" group="{{user}}"
  when: composer.stat.exists == false
