#!/usr/bin/python3
import gi
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-m", "--message", help="Message for notification", required=True)
parser.add_argument("-t", "--title", help="Title for notification", default=__file__)
parser.add_argument("-e", "--header", help="Header for notification message", default="")
parser.set_defaults()
args = parser.parse_args()

gi.require_version('Notify', '0.7')
from gi.repository import Notify
Notify.init(args.title)
Hello = Notify.Notification.new(args.header, args.message, "dialog-information")
Hello.show()
