---
- name: Install vim
  apt: pkg=vim state=installed
  register: vim

- name: write vimrc
  copy: src=vimrc dest=/home/{{ user }}/.vimrc owner={{ user }} group={{ user }} mode=0644

- name: set vim as editor
  shell: >
    echo 'export EDITOR=/usr/bin/vim' >> /home/{{user}}/.profile \
    echo 'export VISUAL=/usr/bin/vim' >> /home/{{user}}/.profile
  when: vim.changed

- name: Install Pathogen
  git: repo=https://github.com/tpope/vim-pathogen depth=1 dest=/home/{{user}}/.vim/autoload
  when: vim.changed

- name: Move Pathogen
  shell: "mv /home/{{user}}/.vim/autoload/autoload/* /home/{{user}}/.vim/autoload"
  when: vim.changed
 
- name: Remove Pathogen repo
  shell: "rm -rf /home/{{user}}/.vim/autoload/autoload"
  when: vim.changed

- name: create vim bundle diretory
  shell: "mkdir /home/{{user}}/.vim/bundle"
  when: vim.changed

- name: Install EasyMotion
  git: repo=https://github.com/Lokaltog/vim-easymotion depth=1 dest=/home/{{user}}/.vim/bundle/easymotion
  when: vim.changed
