---
- name: install git
  apt: "pkg={{item}} state=installed"
  with_items: 
    - git
    - gitk  
    - kdiff3-qt

- name: git global config
  sudo_user: "{{user}}"
  shell: "git config --global {{item}}"
  with_items:
    - 'user.email "stevenmichaeldevine@gmail.com"'
    - 'user.name "Steven Devine"'
    - 'push.default simple'
    - 'diff.tool kdiff3'
    - 'difftool.prompt false'
    - 'alias.d difftool'
  changed_when: False
